// ADARA Cosmética Natural — catálogo de productos
// NOTA: catálogo parcial extraído del PDF "Revista 2026". Faltan productos
// por agregar y los precios mayoristas son de EJEMPLO (marcados wholesaleIsPlaceholder)
// hasta que el cliente confirme la lista real.

const CATEGORIES = [
  { id: "todos", label: "Todos", icon: "sparkles" },
  { id: "cabello", label: "Cabello", icon: "droplet" },
  { id: "rostro", label: "Rostro", icon: "smile" },
  { id: "corporal", label: "Corporal", icon: "heart" },
  { id: "jabones", label: "Jabones", icon: "package" },
  { id: "aceites", label: "Aceites", icon: "flask" },
  { id: "limitada", label: "Edición limitada", icon: "star" },
];

// Utilidad: genera precio mayorista placeholder (20% menos) SOLO para
// maquetar el prototipo. Debe reemplazarse por la lista real del cliente.
function ph(retail) {
  return Math.round(retail * 0.8 * 100) / 100;
}

const PRODUCTS = [
  // ---------- CABELLO: líneas en kit (shampoo + acondicionador + crema) ----------
  {
    id: "cab-romero-cebolla",
    name: "Romero y Cebolla",
    category: "cabello",
    tag: "kit ahorro",
    color: "#F3D9DE",
    description: "Línea capilar 100% artesanal a base de romero y cebolla, ideal para fortalecer y estimular el crecimiento.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 13.99, wholesalePrice: ph(13.99) },
      { label: "Individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.25, wholesalePrice: ph(8.25) },
      { label: "Individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-keratina",
    name: "Keratina",
    category: "cabello",
    tag: "kit ahorro",
    color: "#E9C9D6",
    description: "Línea de keratina 100% artesanal para cabello liso, suave y con brillo.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 13.99, wholesalePrice: ph(13.99) },
      { label: "Individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.25, wholesalePrice: ph(8.25) },
      { label: "Individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-fresa",
    name: "Fresa",
    category: "cabello",
    tag: "kit ahorro",
    color: "#F6C9CE",
    description: "Línea capilar con esencia de fresa, nutre e hidrata dejando un aroma dulce y fresco.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 13.99, wholesalePrice: ph(13.99) },
      { label: "Individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.25, wholesalePrice: ph(8.25) },
      { label: "Individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-manzanilla-miel",
    name: "Manzanilla y Miel",
    category: "cabello",
    tag: "kit ahorro",
    color: "#EFE6C8",
    description: "Línea capilar con manzanilla y miel, ideal para iluminar tonos claros y suavizar el cabello.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 13.99, wholesalePrice: ph(13.99) },
      { label: "Individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.25, wholesalePrice: ph(8.25) },
      { label: "Individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-cebolla-jengibre",
    name: "Cebolla y Jengibre",
    category: "cabello",
    tag: "kit ahorro",
    color: "#E8D3E0",
    description: "Línea capilar con cebolla y jengibre, estimula el cuero cabelludo y fortalece la raíz.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 13.99, wholesalePrice: ph(13.99) },
      { label: "Individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.25, wholesalePrice: ph(8.25) },
      { label: "Individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-bomba-herbal",
    name: "Bomba Herbal",
    category: "cabello",
    tag: "kit ahorro",
    color: "#D8C4B0",
    description: "Línea capilar herbal intensiva para cabello debilitado, con romero, cebolla, jengibre y canela.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 14.99, wholesalePrice: ph(14.99) },
      { label: "Shampoo individual 500ml", price: 5.99, wholesalePrice: ph(5.99) },
      { label: "Acondicionador/crema individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.75, wholesalePrice: ph(8.75) },
      { label: "Shampoo individual 250ml", price: 3.50, wholesalePrice: ph(3.50) },
      { label: "Acondicionador/crema individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-balsamo",
    name: "Bálsamo Anticaspa",
    category: "cabello",
    tag: "anticaspa",
    color: "#D9E0C8",
    description: "Línea capilar de bálsamo y carbón, formulada para ayudar a controlar la caspa.",
    variants: [
      { label: "Kit 500ml (shampoo + acond. + crema)", price: 13.99, wholesalePrice: ph(13.99) },
      { label: "Individual 500ml", price: 4.99, wholesalePrice: ph(4.99) },
      { label: "Kit 250ml (shampoo + acond. + crema)", price: 8.25, wholesalePrice: ph(8.25) },
      { label: "Individual 250ml", price: 2.99, wholesalePrice: ph(2.99) },
    ],
  },
  {
    id: "cab-sabila",
    name: "Sábila Duo",
    category: "cabello",
    tag: "duo",
    color: "#D9E3D2",
    description: "Shampoo y acondicionador de sábila, hidratación natural para todo tipo de cabello.",
    variants: [
      { label: "Duo 500ml (shampoo + acond.)", price: 9.49, wholesalePrice: ph(9.49) },
      { label: "Duo 250ml (shampoo + acond.)", price: 5.49, wholesalePrice: ph(5.49) },
      { label: "Individual", price: 4.99, wholesalePrice: ph(4.99) },
    ],
  },
  {
    id: "cab-carbon",
    name: "Carbón Activado Duo",
    category: "cabello",
    tag: "duo",
    color: "#C9C3C6",
    description: "Shampoo de carbón activado y keratina + acondicionador de carbón y bálsamo, limpieza profunda.",
    variants: [
      { label: "Duo 500ml (shampoo + acond.)", price: 9.49, wholesalePrice: ph(9.49) },
      { label: "Duo 250ml (shampoo + acond.)", price: 5.49, wholesalePrice: ph(5.49) },
      { label: "Individual", price: 4.99, wholesalePrice: ph(4.99) },
    ],
  },
  {
    id: "cab-tonico",
    name: "Tónico Capilar para el Crecimiento",
    category: "cabello",
    color: "#D6B79A",
    description: "Tónico de cebolla, jengibre, romero, canela y cola de caballo. Presentación de 250ml.",
    variants: [{ label: "250ml", price: 3.49, wholesalePrice: ph(3.49) }],
  },
  {
    id: "cab-mascarilla",
    name: "Mascarilla Capilar de Cacao",
    category: "cabello",
    color: "#B9835F",
    description: "Con cacao, manteca de karité y vitamina E. Nutre profundamente, reduce resequedad y frizz. 8 onzas.",
    variants: [{ label: "8 onzas", price: 4.99, wholesalePrice: ph(4.99) }],
  },

  // ---------- ACEITES ----------
  {
    id: "ace-naranja",
    name: "Aceite Esencial de Naranja",
    category: "aceites",
    color: "#F2C879",
    description: "Presentación en gotero de vidrio, ideal para rostro o piel.",
    variants: [{ label: "Gotero", price: 6.50, wholesalePrice: ph(6.50) }],
  },
  {
    id: "ace-jojoba",
    name: "Aceite Esencial de Jojoba",
    category: "aceites",
    color: "#2A2620",
    description: "Presentación en gotero de vidrio, ideal para rostro o piel.",
    variants: [{ label: "Gotero", price: 6.50, wholesalePrice: ph(6.50) }],
  },
  {
    id: "ace-almendra",
    name: "Aceite Esencial de Almendra",
    category: "aceites",
    color: "#F0CDBE",
    description: "Presentación en gotero de vidrio, ideal para rostro o piel.",
    variants: [{ label: "Gotero", price: 6.50, wholesalePrice: ph(6.50) }],
  },
  {
    id: "ace-arbol-te",
    name: "Aceite Esencial de Árbol de Té",
    category: "aceites",
    color: "#2A2620",
    description: "Presentación en gotero de vidrio, ideal para rostro o piel.",
    variants: [{ label: "Gotero", price: 6.50, wholesalePrice: ph(6.50) }],
  },
  {
    id: "ace-coco",
    name: "Aceite de Coco",
    category: "aceites",
    color: "#F4DFA6",
    description: "Dos presentaciones, para piel y cabello.",
    variants: [
      { label: "120ml", price: 3.00, wholesalePrice: ph(3.00) },
      { label: "250ml", price: 6.00, wholesalePrice: ph(6.00) },
    ],
  },

  // ---------- CORPORAL ----------
  {
    id: "corp-scrub-naranja",
    name: "Scrub Sugar de Naranja",
    category: "corporal",
    color: "#F0A25A",
    description: "Exfolia suavemente la piel, eliminando células muertas e impurezas. Contenido: 8 onzas.",
    variants: [{ label: "8 onzas", price: 4.99, wholesalePrice: ph(4.99) }],
  },
  {
    id: "corp-redu-gel",
    name: "Redu-Gel",
    category: "corporal",
    color: "#BFD6C2",
    description: "Ayuda a reducir medidas en zonas críticas, mejora la flacidez y ayuda a prevenir celulitis y estrías.",
    variants: [{ label: "Frasco", price: 4.99, wholesalePrice: ph(4.99) }],
  },
  {
    id: "corp-avena-miel",
    name: "Exfoliante de Avena y Miel",
    category: "corporal",
    color: "#E9DCC3",
    description: "Exfoliante en crema corporal, hidratante y suavizante. 227 gramos.",
    variants: [{ label: "227g", price: 4.99, wholesalePrice: ph(4.99) }],
  },
  {
    id: "corp-crema-coco",
    name: "Crema Corporal de Coco y Vitamina E",
    category: "corporal",
    color: "#F6D9C4",
    description: "Nutre profundamente la piel y le da brillo natural. Presentación de 4 onzas.",
    variants: [{ label: "4 onzas", price: 3.49, wholesalePrice: ph(3.49) }],
  },
  {
    id: "corp-filtro-solar",
    name: "Crema con Filtro Solar 45",
    category: "corporal",
    color: "#F2D9A0",
    description: "Enriquecida con vitamina E y aceite de coco, protege contra rayos UV. 250ml.",
    variants: [{ label: "250ml", price: 5.99, wholesalePrice: ph(5.99) }],
  },

  // ---------- ROSTRO ----------
  {
    id: "rostro-agua-micelar",
    name: "Agua Micelar",
    category: "rostro",
    color: "#CFE3C4",
    description: "Con extracto de aloe vera, vitamina E e infusión herbal. Limpia y desmaquilla el rostro. 200ml.",
    variants: [{ label: "200ml", price: 4.99, wholesalePrice: ph(4.99) }],
  },
  {
    id: "rostro-espuma-fresa",
    name: "Espuma Facial de Fresa",
    category: "rostro",
    color: "#F5C6D0",
    description: "Espuma facial 100% artesanal, limpia y suaviza el rostro.",
    variants: [{ label: "Frasco", price: 3.49, wholesalePrice: ph(3.49) }],
  },
  {
    id: "rostro-baba-caracol",
    name: "Crema Facial con Baba de Caracol",
    category: "rostro",
    color: "#CDE0C6",
    description: "Hidrata, suaviza y aclara el rostro.",
    variants: [{ label: "Frasco", price: 3.25, wholesalePrice: ph(3.25) }],
  },

  // ---------- JABONES ----------
  {
    id: "jabon-balsamo",
    name: "Jabón de Bálsamo",
    category: "jabones",
    color: "#C9D6BC",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-coco",
    name: "Jabón de Coco",
    category: "jabones",
    color: "#EFE7D8",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-avena-miel",
    name: "Jabón de Avena y Miel",
    category: "jabones",
    color: "#F1EADB",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-bicarbonato",
    name: "Jabón de Bicarbonato",
    category: "jabones",
    color: "#F2F1EC",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-carbon",
    name: "Jabón de Carbón Activado",
    category: "jabones",
    color: "#3B3B3B",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-curcuma",
    name: "Jabón de Cúrcuma",
    category: "jabones",
    color: "#E8A23C",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-sabila-pepino",
    name: "Jabón de Sábila y Pepino",
    category: "jabones",
    color: "#9BC77C",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-arroz-vitE",
    name: "Jabón de Arroz y Vitamina E",
    category: "jabones",
    color: "#F1E5CF",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },
  {
    id: "jabon-rosa-mosqueta",
    name: "Jabón de Rosa Mosqueta",
    category: "jabones",
    color: "#EFB8C2",
    description: "Jabón artesanal en barra de 125gr.",
    variants: [{ label: "125gr", price: 2.99, wholesalePrice: ph(2.99) }],
  },

  // ---------- EDICIÓN LIMITADA ----------
  {
    id: "limitada-ejemplo",
    name: "Producto edición limitada (ejemplo — pendiente info real)",
    category: "limitada",
    tag: "edición limitada",
    color: "#D8C89A",
    description: "Espacio reservado para el producto de temporada, elaborado una sola vez al año por lo escaso de su materia prima. Reemplazar con el producto real, su descripción e imagen cuando esté listo.",
    variants: [{ label: "Presentación única", price: 0, wholesalePrice: 0 }],
  },
];
